# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20160901_0948'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='link',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='评论的链接'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.Comment', verbose_name='被评论的内容'),
        ),
    ]
